openapi: 3.0.3
info:
  title: Xone Epochs Module API
  version: 1.0.0
  description: API for querying Xone blockchain epochs (periodic events).
servers:
  - url: http://3.0.124.23:1317
    description: Xone REST server (LCD endpoint)

paths:
  # 查询所有 Epoch 信息
  /evmos/epochs/v1/epochs:
    get:
      tags:
        - Epochs
      summary: List all epochs
      responses:
        '200':
          description: Successfully retrieved epochs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpochsResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # 查询当前 Epoch 信息
  /evmos/epochs/v1/current_epoch:
    get:
      tags:
        - Epochs
      summary: Get current epoch information
      parameters:
        - name: identifier
          in: query
          required: true
          description: Epoch identifier (e.g.,'hour', 'day', 'week')
          schema:
            type: string
            example: "day"
      responses:
        '200':
          description: Successfully retrieved current epoch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentEpochResponse'
        '500':
          description: Epoch info not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # Epoch 数据结构
    Epoch:
      type: object
      properties:
        identifier:
          type: string
          example: "day"
        start_time:
          type: string
          format: date-time
          example: "2023-10-01T00:00:00Z"
        duration:
          type: string
          example: "86400s"
        current_epoch:
          type: string
          example: "123"
        current_epoch_start_time:
          type: string
          format: date-time
          example: "2023-10-01T00:00:00Z"
        epoch_counting_started:
          type: boolean
          example: true
        current_epoch_start_height:
          type: string
          example: 1000

    # 响应模板
    EpochsResponse:
      type: object
      properties:
        epochs:
          type: array
          items:
            $ref: '#/components/schemas/Epoch'
        pagination:
          type: object
          properties:
            next_key:
              type: string
              example: "next_key"
            total:
              type: integer
              example: 100

    CurrentEpochResponse:
      type: object
      properties:
        current_epoch:
          type: string
          example: "123"

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 5
        message:
          type: string
          example: "epoch info not found:"
        details:
          type: array
          items:
            type: object