export const EXTERNAL_LINKS = {
  docs: "/",
  Scan: "https://xonescan.com/",
  Faucet: "https://faucet.xone.org/",
  Forum: "https://forum.xone.org/",
  Status: "https://status.xone.org",

  Support: "support@xone.org",
  Official: "hello@xone.org",
  Job: "job@xone.org",
  Busines: "busines@xone.org",
  Compliance: "compliance@xone.org",
  Labs: "labs@xone.org",
  Grants: "grants@xone.org",
  
  TokenUp: "https://tokenup.org/en",
  RainLink: "https://rainlink.co/",
  SwapX: "https://swapx.exchange/en",
  NFT_Market: "https://nft.xone.org/en",
  Settlement: "https://www.payout.plus/",
  Xone_ID: "https://xid.world/",
  
  Github: "https://github.com/hello-xone/",
  Telegram: "https://t.me/hello_xonechain",
  Twitter: "https://x.com/xone_chain",
  Discord: "https://discord.com/invite/Du9y2GHV",
  Youtube: "https://www.youtube.com/@HelloXone",
  Reddit: "https://www.reddit.com/r/XoneChain/",
  Medium: "https://medium.com/@xone_chain",
  ChatMe: "https://share.chatme.global/share/group/ztgqmws2k?lang=en&mode=light",
  Coingecko: "https://www.coingecko.com/en/chains/xone",
};
