name: Deploy to Cloudflare
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Wrangler
        run: npm add -g wrangler
      - name: Install Next
        run: npm add -g next
      - name: Install Pnpm
        run: npm add -g pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Repair cloudflare-nextjs
        run: pnpm install --save-dev @cloudflare/next-on-pages
      - name: Build
        run: npx @cloudflare/next-on-pages
      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy --branch=main
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
